name: DevtoGitHub

on:
  schedule:
    - cron: "0 0 * * *" # Run daily, adjust as needed
  workflow_dispatch:
  push:
    branches: ["check-2"]

jobs:
  save_articles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run DevtoGitHub
        uses: ./
        with:
          devApiKey: ${{ secrets.DEV_TOKEN }}
          saveArticles: false
